pipeline {
    agent { 
        label 'buildconductor-iib'
    }

    stages {
       stage('Checkout'){
            steps {
                checkout(poll: true, [$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: '/home/jenkins/workspace/build_home/load']], submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/greghodgkinson/tempconvert-iib-example.git']]])
            }
          
       }     
        stage('Build BAR') {
            steps {
            sh "/prolifics/buildconductor/iib/run-automation.sh build tempconvert TemperatureConverter" 
          }
        }
        stage('Override and Deploy BAR') {
            steps {
                sh "/prolifics/buildconductor/iib/run-automation.sh overrideAndDeploy tempconvert 10.0.12.60 30161 IIB_NODE IIB_SERVER iibuser iibuser TemperatureConverter TemperatureConverter/overrides/development.properties"

          }
        }
    }
}
